{% set name = "sophios" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PolusAI/workflow-inference-compiler/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 54e8bd0cfd6b0243bce19c0b878a8506687d737242f6a26a5485f86f2acb787b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - pip 
    - wheel 
    - versioneer ==0.29
    - tomli
  run:
    - python >={{ python_min }}
    - python-graphviz
    - jsonschema
    - toil
    - pyyaml
    - requests <=2.31.0
    - mergedeep
    - networkx
    - cwl-utils >=0.32
    - typeguard
    - pydantic >=2.6
    - pydantic-settings
    - ruamel.yaml.clib
    - fastapi
    - docker-py
    - podman-py
    - python-jose
    - uvicorn
    - orjson

test:
  imports:
    - sophios
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sophios/
  summary: DSL for inferring the edges of a CWL workflow DAG
  dev_url: https://github.com/PolusAI/workflow-inference-compiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sameeul
